name: Pre-release

on:
  workflow_run:
    workflows:
      - Test
    tag:
      - 'v[0-9]+.[0-9]+.[0-9]+-pre.[0-9]+'
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Build
        run: |
          make build-pre-release
          make dist

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: true

      - name: Upload Release Assets
        id: upload-release-assets
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./dist/*.tar.gz

  fail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - run: |
          echo '::error::Testing was failed'
          exit 1
