name: Release

on:
  workflow_run:
    workflows:
      - Test
    tag:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

  fail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - run: |
          echo '::error::Testing was failed'
          exit 1
